GET http://localhost:3000/todos/

###

DELETE http://localhost:3000/todos/10

###

GET http://localhost:3000/todos/5

###


POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 1,
  "todo": "Watch Movie",
  "priority": "LOW",
  "status": "TO DO"
  
}

###

PUT http://localhost:3000/todos/3/
Content-Type: application/json

{
    "status": "DONE"
}